apiVersion: apps/v1
kind: Deployment
metadata:
  name: kantox-challenge-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kantox-challenge
  template:
    metadata:
      labels:
        app: kantox-challenge
    spec:
      containers:
      - name: my-api
        image: aspeak03524/kantox-challenge:my-api-dual-2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: my-aux
        image: aspeak03524/kantox-challenge:my-aux-latest-2
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: kantox-challenge-api-service
spec:
  selector:
    app: kantox-challenge
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kantox-challenge-aux-service
spec:
  selector:
    app: kantox-challenge
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP