apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: andrew-kantox-cluster 
  region: eu-south-2 

nodeGroups:
  - name: public-nodegroup
    instanceType: t3.medium 
    desiredCapacity: 2
    minSize: 2
    maxSize: 4

  - name: private-nodegroup
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true