version: '3.8'
services:
  my-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - my-network
    depends_on:
      - my-aux
  my-aux:
    build:
      context: ./Auxiliary
      dockerfile: Dockerfile
    ports:
      - '4000:80'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge