name: CI/CD Pipeline - Build, Test, and Deploy Specific Tags

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-test:
    name: Build and Test Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build App Image
        id: build-app
        env:
          DOCKERHUB_REPOSITORY: aspeak03524/kantox-challenge
          IMAGE_TAG: my-api-dual-2 # Hardcoded tag
        run: |
          docker build -t aspeak03524/kantox-challenge:my-api-dual-2 -f app/Dockerfile app
          docker push aspeak03524/kantox-challenge:my-api-dual-2

      - name: Build Auxiliary Image
        id: build-auxiliary
        env:
          DOCKERHUB_REPOSITORY: aspeak03524/kantox-challenge
          IMAGE_TAG: my-aux-latest-2 # Hardcoded tag
        run: |
          docker build -t aspeak03524/kantox-challenge:my-aux-latest-2 -f auxiliary/Dockerfile background
          docker push aspeak03524/kantox-challenge:my-aux-latest-2

      - name: Run Tests (App)
        run: |
          docker run --rm aspeak03524/kantox-challenge:my-api-dual-2 /bin/sh -c "echo 'Running App tests...'; exit 0" # Replace with your actual test commands

      - name: Run Tests (Auxiliary)
        run: |
          docker run --rm aspeak03524/kantox-challenge:my-aux-latest-2 /bin/sh -c "echo 'Running Auxiliary tests...'; exit 0" # Replace with your actual test commands

  deploy-to-eks:
    name: Deploy to EKS with Specific Tags
    runs-on: self-hosted # Use your self-hosted runner
    needs: build-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-2

      - name: Update Kubernetes Deployment with Specific Tags
        env:
          DOCKERHUB_REPOSITORY: aspeak03524/kantox-challenge
          APP_IMAGE_TAG: my-api-dual-2
          AUXILIARY_IMAGE_TAG: my-aux-latest-2
        run: |
          aws eks update-kubeconfig --name andrew-kantox-cluster --region eu-south-2
          # Replace the image tags within the kubernetes/deployment.yml file
          sed -i "s|YOUR_APP_IMAGE_TAG|${DOCKERHUB_REPOSITORY}:${APP_IMAGE_TAG}|g" kubernetes/deployment.yml
          sed -i "s|YOUR_AUXILIARY_IMAGE_TAG|${DOCKERHUB_REPOSITORY}:${AUXILIARY_IMAGE_TAG}|g" kubernetes/deployment.yml
          # Apply the deployment.yml file from the kubernetes folder
          kubectl apply -f kubernetes/deployment.yml -n default
          # Update the config map
          kubectl create configmap service-version \
          --from-literal=APP_VERSION=${APP_IMAGE_TAG} \
          --from-literal=AUXILIARY_VERSION=${AUXILIARY_IMAGE_TAG} \
          -n default --dry-run=client -o yaml | kubectl apply -f -
